<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Data types, part 1 | Using R for data analysis</title>
  <meta name="description" content="This course teaches the basics of R, an open-source and free environment for statistical analyses. In this course we also teach the basics transparent and reproducible research. For this, we teach RMarkdown, a tool to make dynamic reports in R." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Data types, part 1 | Using R for data analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This course teaches the basics of R, an open-source and free environment for statistical analyses. In this course we also teach the basics transparent and reproducible research. For this, we teach RMarkdown, a tool to make dynamic reports in R." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Data types, part 1 | Using R for data analysis" />
  
  <meta name="twitter:description" content="This course teaches the basics of R, an open-source and free environment for statistical analyses. In this course we also teach the basics transparent and reproducible research. For this, we teach RMarkdown, a tool to make dynamic reports in R." />
  



<meta name="date" content="2024-05-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basics-of-r.html"/>
<link rel="next" href="data-types-part-2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this course</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teachers"><i class="fa fa-check"></i>Teachers</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#goals-topics"><i class="fa fa-check"></i>Goals &amp; Topics</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#programme"><i class="fa fa-check"></i>Programme</a>
<ul>
<li class="chapter" data-level="0.0.1" data-path="index.html"><a href="index.html#sixth-nki-edition-june-3rd-4th-6th-and-7th-2024"><i class="fa fa-check"></i><b>0.0.1</b> Sixth NKI edition, June 3rd, 4th, 6th, and 7th 2024</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="basics-of-r.html"><a href="basics-of-r.html"><i class="fa fa-check"></i><b>1</b> Basics of R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="basics-of-r.html"><a href="basics-of-r.html#data-sets"><i class="fa fa-check"></i><b>1.1</b> Data sets</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="basics-of-r.html"><a href="basics-of-r.html#pulse"><i class="fa fa-check"></i><b>1.1.1</b> Pulse</a></li>
<li class="chapter" data-level="1.1.2" data-path="basics-of-r.html"><a href="basics-of-r.html#survey"><i class="fa fa-check"></i><b>1.1.2</b> Survey</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="basics-of-r.html"><a href="basics-of-r.html#introduction"><i class="fa fa-check"></i><b>1.2</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="basics-of-r.html"><a href="basics-of-r.html#why-this-course"><i class="fa fa-check"></i><b>1.2.1</b> Why this course?</a></li>
<li class="chapter" data-level="1.2.2" data-path="basics-of-r.html"><a href="basics-of-r.html#what-is-r"><i class="fa fa-check"></i><b>1.2.2</b> What is R?</a></li>
<li class="chapter" data-level="1.2.3" data-path="basics-of-r.html"><a href="basics-of-r.html#r-a-short-history"><i class="fa fa-check"></i><b>1.2.3</b> <em>R</em>: a short history</a></li>
<li class="chapter" data-level="1.2.4" data-path="basics-of-r.html"><a href="basics-of-r.html#r-is-open-source"><i class="fa fa-check"></i><b>1.2.4</b> R is Open Source</a></li>
<li class="chapter" data-level="1.2.5" data-path="basics-of-r.html"><a href="basics-of-r.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.2.5</b> R and RStudio</a></li>
<li class="chapter" data-level="1.2.6" data-path="basics-of-r.html"><a href="basics-of-r.html#rstudio-packages"><i class="fa fa-check"></i><b>1.2.6</b> RStudio packages</a></li>
<li class="chapter" data-level="1.2.7" data-path="basics-of-r.html"><a href="basics-of-r.html#course-overview"><i class="fa fa-check"></i><b>1.2.7</b> Course overview</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="basics-of-r.html"><a href="basics-of-r.html#basics"><i class="fa fa-check"></i><b>1.3</b> Basics</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="basics-of-r.html"><a href="basics-of-r.html#r-as-a-calculator"><i class="fa fa-check"></i><b>1.3.1</b> R as a calculator</a></li>
<li class="chapter" data-level="1.3.2" data-path="basics-of-r.html"><a href="basics-of-r.html#variables"><i class="fa fa-check"></i><b>1.3.2</b> Variables</a></li>
<li class="chapter" data-level="1.3.3" data-path="basics-of-r.html"><a href="basics-of-r.html#vectors"><i class="fa fa-check"></i><b>1.3.3</b> Vectors</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="basics-of-r.html"><a href="basics-of-r.html#projects-and-scripts"><i class="fa fa-check"></i><b>1.4</b> Projects and scripts</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="basics-of-r.html"><a href="basics-of-r.html#projects"><i class="fa fa-check"></i><b>1.4.1</b> Projects</a></li>
<li class="chapter" data-level="1.4.2" data-path="basics-of-r.html"><a href="basics-of-r.html#reading-data"><i class="fa fa-check"></i><b>1.4.2</b> Reading data</a></li>
<li class="chapter" data-level="1.4.3" data-path="basics-of-r.html"><a href="basics-of-r.html#scripts"><i class="fa fa-check"></i><b>1.4.3</b> Scripts</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="basics-of-r.html"><a href="basics-of-r.html#data-frames-basics"><i class="fa fa-check"></i><b>1.5</b> Data frames (basics)</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="basics-of-r.html"><a href="basics-of-r.html#exploring-datasets"><i class="fa fa-check"></i><b>1.5.1</b> Exploring datasets</a></li>
<li class="chapter" data-level="1.5.2" data-path="basics-of-r.html"><a href="basics-of-r.html#extracting"><i class="fa fa-check"></i><b>1.5.2</b> Extracting</a></li>
<li class="chapter" data-level="1.5.3" data-path="basics-of-r.html"><a href="basics-of-r.html#example-data"><i class="fa fa-check"></i><b>1.5.3</b> Example data</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="basics-of-r.html"><a href="basics-of-r.html#basic-data-types"><i class="fa fa-check"></i><b>1.6</b> Basic data types</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="basics-of-r.html"><a href="basics-of-r.html#types"><i class="fa fa-check"></i><b>1.6.1</b> Types</a></li>
<li class="chapter" data-level="1.6.2" data-path="basics-of-r.html"><a href="basics-of-r.html#vector-classes"><i class="fa fa-check"></i><b>1.6.2</b> Vector classes</a></li>
<li class="chapter" data-level="1.6.3" data-path="basics-of-r.html"><a href="basics-of-r.html#character-data"><i class="fa fa-check"></i><b>1.6.3</b> Character data</a></li>
<li class="chapter" data-level="1.6.4" data-path="basics-of-r.html"><a href="basics-of-r.html#factor---categorical-data"><i class="fa fa-check"></i><b>1.6.4</b> Factor - categorical data</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="basics-of-r.html"><a href="basics-of-r.html#functions-and-help-files"><i class="fa fa-check"></i><b>1.7</b> Functions and help files</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="basics-of-r.html"><a href="basics-of-r.html#function-arguments"><i class="fa fa-check"></i><b>1.7.1</b> Function arguments</a></li>
<li class="chapter" data-level="1.7.2" data-path="basics-of-r.html"><a href="basics-of-r.html#getting-help-for-a-function"><i class="fa fa-check"></i><b>1.7.2</b> Getting help for a function</a></li>
<li class="chapter" data-level="1.7.3" data-path="basics-of-r.html"><a href="basics-of-r.html#specifying-arguments-by-name"><i class="fa fa-check"></i><b>1.7.3</b> Specifying arguments by name</a></li>
<li class="chapter" data-level="1.7.4" data-path="basics-of-r.html"><a href="basics-of-r.html#default-arguments"><i class="fa fa-check"></i><b>1.7.4</b> Default arguments</a></li>
<li class="chapter" data-level="1.7.5" data-path="basics-of-r.html"><a href="basics-of-r.html#the-...-argument"><i class="fa fa-check"></i><b>1.7.5</b> (*) the <code>...</code> argument</a></li>
<li class="chapter" data-level="1.7.6" data-path="basics-of-r.html"><a href="basics-of-r.html#other-help-file-aspects"><i class="fa fa-check"></i><b>1.7.6</b> Other help file aspects</a></li>
<li class="chapter" data-level="1.7.7" data-path="basics-of-r.html"><a href="basics-of-r.html#help-search"><i class="fa fa-check"></i><b>1.7.7</b> Help search</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-types-part-1.html"><a href="data-types-part-1.html"><i class="fa fa-check"></i><b>2</b> Data types, part 1</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#basic-data-types-cont."><i class="fa fa-check"></i><b>2.1</b> Basic data types (cont.)</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#missing-values"><i class="fa fa-check"></i><b>2.1.1</b> Missing values</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#numeric-vectors"><i class="fa fa-check"></i><b>2.1.2</b> Numeric vectors</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#character-vectors"><i class="fa fa-check"></i><b>2.1.3</b> Character vectors</a></li>
<li class="chapter" data-level="2.1.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#logical-vectors-and-operators"><i class="fa fa-check"></i><b>2.1.4</b> Logical vectors and operators</a></li>
<li class="chapter" data-level="2.1.5" data-path="data-types-part-1.html"><a href="data-types-part-1.html#type-conversions"><i class="fa fa-check"></i><b>2.1.5</b> Type conversions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#vectors-1"><i class="fa fa-check"></i><b>2.2</b> Vectors</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#square-brackets-operator"><i class="fa fa-check"></i><b>2.2.1</b> Square brackets operator</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#class-of-a-vector"><i class="fa fa-check"></i><b>2.2.2</b> (*) Class of a vector</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#other-useful-functions"><i class="fa fa-check"></i><b>2.2.3</b> Other useful functions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#data-frames"><i class="fa fa-check"></i><b>2.3</b> Data frames</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>2.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#creating-a-data-frame"><i class="fa fa-check"></i><b>2.3.2</b> Creating a data frame</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#properties"><i class="fa fa-check"></i><b>2.3.3</b> Properties</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#content"><i class="fa fa-check"></i><b>2.3.4</b> Content</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#matrices"><i class="fa fa-check"></i><b>2.4</b> Matrices</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#what-is-a-matrix"><i class="fa fa-check"></i><b>2.4.1</b> What is a matrix</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#creation"><i class="fa fa-check"></i><b>2.4.2</b> Creation</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#dimensions-2"><i class="fa fa-check"></i><b>2.4.3</b> Dimensions</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#settinggetting-names-of-the-columns-and-rows"><i class="fa fa-check"></i><b>2.4.4</b> Setting/getting names of the columns and rows</a></li>
<li class="chapter" data-level="2.4.5" data-path="data-types-part-1.html"><a href="data-types-part-1.html#getting-matrix-elements"><i class="fa fa-check"></i><b>2.4.5</b> Getting matrix elements</a></li>
<li class="chapter" data-level="2.4.6" data-path="data-types-part-1.html"><a href="data-types-part-1.html#useful-matrix-functions"><i class="fa fa-check"></i><b>2.4.6</b> Useful matrix functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-types-part-2.html"><a href="data-types-part-2.html"><i class="fa fa-check"></i><b>3</b> Data types, part 2</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#r-scripts-and-reports-rmarkdown"><i class="fa fa-check"></i><b>3.1</b> R scripts and reports (Rmarkdown)</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#markdown-r-code-markdown-text-formating-language"><i class="fa fa-check"></i><b>3.1.1</b> Markdown : R code + Markdown text formating language</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#features-of-r-markdown"><i class="fa fa-check"></i><b>3.1.2</b> Features of R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#lists"><i class="fa fa-check"></i><b>3.2</b> Lists</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#what-is-a-list"><i class="fa fa-check"></i><b>3.2.1</b> What is a list</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#creation-1"><i class="fa fa-check"></i><b>3.2.2</b> Creation</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#length"><i class="fa fa-check"></i><b>3.2.3</b> Length</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-types-part-2.html"><a href="data-types-part-2.html#getting-names-of-the-elements"><i class="fa fa-check"></i><b>3.2.4</b> Getting names of the elements</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-types-part-2.html"><a href="data-types-part-2.html#getting-a-single-element"><i class="fa fa-check"></i><b>3.2.5</b> Getting a single element</a></li>
<li class="chapter" data-level="3.2.6" data-path="data-types-part-2.html"><a href="data-types-part-2.html#getting-multiple-elements-as-a-list"><i class="fa fa-check"></i><b>3.2.6</b> (*) Getting multiple elements as a list</a></li>
<li class="chapter" data-level="3.2.7" data-path="data-types-part-2.html"><a href="data-types-part-2.html#removing-an-element"><i class="fa fa-check"></i><b>3.2.7</b> (*) Removing an element</a></li>
<li class="chapter" data-level="3.2.8" data-path="data-types-part-2.html"><a href="data-types-part-2.html#adding-an-element"><i class="fa fa-check"></i><b>3.2.8</b> (*) Adding an element</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#basic-statistical-tests"><i class="fa fa-check"></i><b>3.3</b> Basic statistical tests</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#statistical-methods-with-r"><i class="fa fa-check"></i><b>3.3.1</b> Statistical methods with R</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-types-part-2.html"><a href="data-types-part-2.html#regression-and-formula-objects"><i class="fa fa-check"></i><b>3.4</b> Regression and formula objects</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#formula-objects"><i class="fa fa-check"></i><b>3.4.1</b> Formula objects</a></li>
<li class="chapter" data-level="3.4.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#simple-linear-regression"><i class="fa fa-check"></i><b>3.4.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="3.4.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#multiple-regression-and-prediction"><i class="fa fa-check"></i><b>3.4.3</b> Multiple regression and prediction</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="data-types-part-2.html"><a href="data-types-part-2.html#factors-advanced"><i class="fa fa-check"></i><b>3.5</b> Factors (advanced)</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#factors-revisited"><i class="fa fa-check"></i><b>3.5.1</b> Factors revisited</a></li>
<li class="chapter" data-level="3.5.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#anova-and-regression-with-factors"><i class="fa fa-check"></i><b>3.5.2</b> ANOVA and regression with factors</a></li>
<li class="chapter" data-level="3.5.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#generalized-linear-models-and-survival"><i class="fa fa-check"></i><b>3.5.3</b> (*) Generalized linear models and survival</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="functions.html"><a href="functions.html#user-defined-functions"><i class="fa fa-check"></i><b>4.1</b> User-defined Functions</a></li>
<li class="chapter" data-level="4.2" data-path="functions.html"><a href="functions.html#control-flow-constructs"><i class="fa fa-check"></i><b>4.2</b> (*) Control flow constructs</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="functions.html"><a href="functions.html#sequential-execution"><i class="fa fa-check"></i><b>4.2.1</b> Sequential execution</a></li>
<li class="chapter" data-level="4.2.2" data-path="functions.html"><a href="functions.html#conditional-execution-if"><i class="fa fa-check"></i><b>4.2.2</b> Conditional execution: if</a></li>
<li class="chapter" data-level="4.2.3" data-path="functions.html"><a href="functions.html#conditional-execution-ifelse"><i class="fa fa-check"></i><b>4.2.3</b> Conditional execution: if/else</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="functions.html"><a href="functions.html#apply-family-apply-lapply-sapply-tapply"><i class="fa fa-check"></i><b>4.3</b> <code>apply</code> family: apply, lapply, sapply, tapply</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="functions.html"><a href="functions.html#applyx-margin-fun"><i class="fa fa-check"></i><b>4.3.1</b> apply(X, MARGIN, FUN, …)</a></li>
<li class="chapter" data-level="4.3.2" data-path="functions.html"><a href="functions.html#sapplyx-fun"><i class="fa fa-check"></i><b>4.3.2</b> sapply(X, FUN, …)</a></li>
<li class="chapter" data-level="4.3.3" data-path="functions.html"><a href="functions.html#lapplyx-fun-apply-a-function-to-a-listvector"><i class="fa fa-check"></i><b>4.3.3</b> lapply(X, FUN, …) : apply a function to a list/vector</a></li>
<li class="chapter" data-level="4.3.4" data-path="functions.html"><a href="functions.html#tapplyx-index-fun-apply-a-function-to-a-vector-according-to-groups-of-index"><i class="fa fa-check"></i><b>4.3.4</b> tapply(X, INDEX, FUN, …) : apply a function to a vector, according to groups of INDEX</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="functions.html"><a href="functions.html#type-checking"><i class="fa fa-check"></i><b>4.4</b> Type checking</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="functions.html"><a href="functions.html#is.-family-functions"><i class="fa fa-check"></i><b>4.4.1</b> is.* family functions</a></li>
<li class="chapter" data-level="4.4.2" data-path="functions.html"><a href="functions.html#stopwarning"><i class="fa fa-check"></i><b>4.4.2</b> (*) stop(…)/warning(…)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="functions.html"><a href="functions.html#r-programming"><i class="fa fa-check"></i><b>4.5</b> (*) R programming</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="functions.html"><a href="functions.html#general-coding-conventions"><i class="fa fa-check"></i><b>4.5.1</b> General coding conventions</a></li>
<li class="chapter" data-level="4.5.2" data-path="functions.html"><a href="functions.html#finding-installing-and-loading-packages"><i class="fa fa-check"></i><b>4.5.2</b> Finding, installing and loading packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#character-string-processing-pattern-matching"><i class="fa fa-check"></i>Character string processing &amp; Pattern matching</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#learning-goals"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#quotes-and-escape-characters-characters-with-special-meaning"><i class="fa fa-check"></i>Quotes and escape characters (characters with special meaning)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#character-string"><i class="fa fa-check"></i>Character string</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#paste-sep-collapse-null"><i class="fa fa-check"></i>paste(…, sep = ” “, collapse = NULL):</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#pulse-data-set"><i class="fa fa-check"></i>Pulse data set</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#tolower-toupper-nchar"><i class="fa fa-check"></i>tolower, toupper, nchar</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#split-character-string-strsplitx-split"><i class="fa fa-check"></i>Split character string : strsplit(x, split, …):</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#rbind-cbind-combine-by-rows-or-columns"><i class="fa fa-check"></i>rbind(…), cbind(…) : combine by rows or columns</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#strsplitx-split"><i class="fa fa-check"></i>strsplit(x, split, …)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#do.callwhat-args-execute-function-on-list-of-arguments"><i class="fa fa-check"></i>do.call(what, args, …) : execute function on list of arguments</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#greppattern-x-ignore.case-false-value-false"><i class="fa fa-check"></i>grep(pattern, x, ignore.case = FALSE, value = FALSE, … )</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#greplpattern-x-ignore.case-false"><i class="fa fa-check"></i>grepl(pattern, x, ignore.case = FALSE, …)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#substrx-start-stop-extractreplace-substrings"><i class="fa fa-check"></i>substr(x, start, stop) : extract/replace substrings</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#gsubsubpattern-replacement-x-ignore.case-false"><i class="fa fa-check"></i>gsub/sub(pattern, replacement, x, ignore.case = FALSE, …)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#extra-exercises"><i class="fa fa-check"></i>Extra exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#s3-and-s4-classes"><i class="fa fa-check"></i>S3 and S4 classes</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#learning-goals-1"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#objects"><i class="fa fa-check"></i>Objects</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#s3"><i class="fa fa-check"></i>S3</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#s4"><i class="fa fa-check"></i>S4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#making-errors-the-right-way"><i class="fa fa-check"></i>Making errors the right way</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#annoying-errors"><i class="fa fa-check"></i>Annoying errors</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#how-to-correct-annoying-errors"><i class="fa fa-check"></i>How to correct (annoying) errors</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#dangerous-errors"><i class="fa fa-check"></i>Dangerous errors</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#how-to-avoid-dangerous-errors"><i class="fa fa-check"></i>How to avoid (dangerous) errors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#useful-links"><i class="fa fa-check"></i>Useful links</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using R for data analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-types-part-1" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Data types, part 1<a href="data-types-part-1.html#data-types-part-1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="basic-data-types-cont." class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Basic data types (cont.)<a href="data-types-part-1.html#basic-data-types-cont." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="missing-values" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Missing values<a href="data-types-part-1.html#missing-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Numeric, character, logical vectors, factors might contain elements marked as ‘missing’.</p>
<p><code>NA</code> is a constant which indicates a missing value.</p>
<p><code>NA</code> values can be included in all objects in R.</p>
</div>
<div id="numeric-vectors" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Numeric vectors<a href="data-types-part-1.html#numeric-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Vector: set of values put together in a certain order</p>
<p>Numeric vector: set of <em>numbers</em> put together in a certain order</p>
<p>Below we will see some ways to create numeric vectors.</p>
<div id="sequences-of-numbers" class="section level4 hasAnchor" number="2.1.2.1">
<h4><span class="header-section-number">2.1.2.1</span> Sequences of numbers<a href="data-types-part-1.html#sequences-of-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One way of creating sequences of numbers is to use the operator <code>:</code>. It creates a sequence of consecutive integers starting by the first argument, and ending by the last one. For example:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="data-types-part-1.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span><span class="sc">:</span><span class="dv">17</span></span></code></pre></div>
<pre><code>##  [1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17</code></pre>
<p>It can also be used to create sequences in decreasing order:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="data-types-part-1.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="dv">17</span><span class="sc">:</span><span class="dv">3</span></span></code></pre></div>
<pre><code>##  [1] 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3</code></pre>
<p>Negative arguments are also allowed:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="data-types-part-1.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">3</span><span class="sc">:</span><span class="dv">10</span></span></code></pre></div>
<pre><code>##  [1] -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10</code></pre>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="data-types-part-1.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">2</span><span class="sc">:-</span><span class="dv">7</span></span></code></pre></div>
<pre><code>## [1] -2 -3 -4 -5 -6 -7</code></pre>
<p>So <code>:</code> can be used to create sequences with steps of 1 between elements. Sometimes we want to create sequences with steps of a different value. For this, <code>seq()</code> is useful:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="data-types-part-1.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">3</span>, <span class="at">to =</span> <span class="dv">17</span>, <span class="at">by =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##  [1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17</code></pre>
<p>This creates the same sequence as with <code>3:17</code>. If we wish to use a step of 2, all we do is:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="data-types-part-1.html#cb174-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">3</span>, <span class="at">to =</span> <span class="dv">17</span>, <span class="at">by =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1]  3  5  7  9 11 13 15 17</code></pre>
<p>Above <code>seq()</code> was called by naming the arguments <code>from</code>, <code>to</code> and <code>by</code>. The argument names can be omited if they are given in the expected order <code>from--to--by</code>:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="data-types-part-1.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">3</span>, <span class="at">to =</span> <span class="dv">17</span>, <span class="at">by =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1]  3  5  7  9 11 13 15 17</code></pre>
</div>
<div id="combining-multiple-numbers" class="section level4 hasAnchor" number="2.1.2.2">
<h4><span class="header-section-number">2.1.2.2</span> Combining multiple numbers<a href="data-types-part-1.html#combining-multiple-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Multiple numbers can be combined to create numeric vectors:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="data-types-part-1.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 3 5 7 8</code></pre>
<p>Entries in <code>c()</code> may include any type of number, or operation yielding a number, and the result will be a numeric vector. For example:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="data-types-part-1.html#cb180-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">5</span>, <span class="sc">-</span><span class="fl">2.5</span>, <span class="cn">NA</span>, <span class="dv">7</span><span class="sc">+</span><span class="dv">3</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> )</span>
<span id="cb180-2"><a href="data-types-part-1.html#cb180-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1]  5.0000000 -2.5000000         NA 10.0000000  0.3333333</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="data-types-part-1.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(x)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>Note that a single value is in fact a vector of length 1:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="data-types-part-1.html#cb184-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">7</span></span>
<span id="cb184-2"><a href="data-types-part-1.html#cb184-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(x)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
</div>
<div id="combining-vectors-of-numbers" class="section level4 hasAnchor" number="2.1.2.3">
<h4><span class="header-section-number">2.1.2.3</span> Combining vectors of numbers<a href="data-types-part-1.html#combining-vectors-of-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Multiple vectors can be combined together:</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="data-types-part-1.html#cb186-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span></span>
<span id="cb186-2"><a href="data-types-part-1.html#cb186-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">seq</span>( <span class="dv">10</span>, <span class="dv">90</span>, <span class="dv">10</span> )</span>
<span id="cb186-3"><a href="data-types-part-1.html#cb186-3" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">0</span>, v, w, <span class="cn">NA</span>, <span class="dv">100</span> )</span>
<span id="cb186-4"><a href="data-types-part-1.html#cb186-4" aria-hidden="true" tabindex="-1"></a>res</span></code></pre></div>
<pre><code>##  [1]   0   1   2   3   4   5   6   7   8   9  10  20  30  40  50  60  70  80  90
## [20]  NA 100</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="data-types-part-1.html#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(res)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/01_basic_data_types_cont.tasks.nocode.html#numeric">the task(s)</a>, and check your solution(s) <a href="exercises/01_basic_data_types_cont.tasks.code.html#numeric">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="character-vectors" class="section level3 hasAnchor" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Character vectors<a href="data-types-part-1.html#character-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just like with numeric vectors, there are several ways to construct a character vector. First let us define what a string of characters is.</p>
<div id="string-of-characters" class="section level4 hasAnchor" number="2.1.3.1">
<h4><span class="header-section-number">2.1.3.1</span> String of characters<a href="data-types-part-1.html#string-of-characters" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A character string, or string of characters, is essentially a combination of characters. These can be letters “a”, “A”, “b”, as well as numbers and other character types such as ‘.’ and ’_’. A character string can be defined by declaring it between quotes - they can be double:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="data-types-part-1.html#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Bioinformatics&quot;</span></span></code></pre></div>
<pre><code>## [1] &quot;Bioinformatics&quot;</code></pre>
<p>or single:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="data-types-part-1.html#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;Biostatistics&#39;</span></span></code></pre></div>
<pre><code>## [1] &quot;Biostatistics&quot;</code></pre>
<p>The initial quote must match the last one.</p>
<p>In R everything is case-sensitive, including character strings. This means that ‘Biostatistics’ and ‘biostatistics’ are in fact different strings.</p>
<p>Other examples of character strings are:</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="data-types-part-1.html#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;day1&quot;</span></span></code></pre></div>
<pre><code>## [1] &quot;day1&quot;</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="data-types-part-1.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;June 2024&quot;</span></span></code></pre></div>
<pre><code>## [1] &quot;June 2024&quot;</code></pre>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="data-types-part-1.html#cb198-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;first.And.Second&#39;</span></span></code></pre></div>
<pre><code>## [1] &quot;first.And.Second&quot;</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="data-types-part-1.html#cb200-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;file_name&#39;</span></span></code></pre></div>
<pre><code>## [1] &quot;file_name&quot;</code></pre>
</div>
<div id="character-vector" class="section level4 hasAnchor" number="2.1.3.2">
<h4><span class="header-section-number">2.1.3.2</span> Character vector<a href="data-types-part-1.html#character-vector" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Multiple character strings can be combined to create a character vector using <code>c()</code>. For example:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="data-types-part-1.html#cb202-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;Bioinformatics&quot;</span>, <span class="st">&quot;Biostatistics&quot;</span>, <span class="st">&quot;June2024&quot;</span>, <span class="cn">NA</span>, <span class="st">&quot;particiPants&quot;</span> )</span>
<span id="cb202-2"><a href="data-types-part-1.html#cb202-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] &quot;Bioinformatics&quot; &quot;Biostatistics&quot;  &quot;June2024&quot;       NA              
## [5] &quot;particiPants&quot;</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="data-types-part-1.html#cb204-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(x)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
</div>
</div>
<div id="logical-vectors-and-operators" class="section level3 hasAnchor" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Logical vectors and operators<a href="data-types-part-1.html#logical-vectors-and-operators" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="logical-vectors" class="section level4 hasAnchor" number="2.1.4.1">
<h4><span class="header-section-number">2.1.4.1</span> Logical vectors<a href="data-types-part-1.html#logical-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Elementary logical values are:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="data-types-part-1.html#cb206-1" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="data-types-part-1.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="data-types-part-1.html#cb210-1" aria-hidden="true" tabindex="-1"></a>T</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="data-types-part-1.html#cb212-1" aria-hidden="true" tabindex="-1"></a>F</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>A logical vector can be created by combining logical values with <code>c()</code>:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="data-types-part-1.html#cb214-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="cn">FALSE</span>, F, <span class="cn">NA</span>, <span class="cn">TRUE</span>, T )   </span>
<span id="cb214-2"><a href="data-types-part-1.html#cb214-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] FALSE FALSE    NA  TRUE  TRUE</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="data-types-part-1.html#cb216-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(x)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
</div>
<div id="logical-operators" class="section level4 hasAnchor" number="2.1.4.2">
<h4><span class="header-section-number">2.1.4.2</span> Logical operators<a href="data-types-part-1.html#logical-operators" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="negation" class="section level5 hasAnchor" number="2.1.4.2.1">
<h5><span class="header-section-number">2.1.4.2.1</span> Negation<a href="data-types-part-1.html#negation" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Unary negation operator (denoted <code>!</code>):</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="data-types-part-1.html#cb218-1" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span><span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="data-types-part-1.html#cb220-1" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span><span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="and-operator" class="section level5 hasAnchor" number="2.1.4.2.2">
<h5><span class="header-section-number">2.1.4.2.2</span> AND Operator <code>&amp;</code><a href="data-types-part-1.html#and-operator" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Binary operator AND (denoted <code>&amp;</code>) returns <code>TRUE</code> result when <em>all</em> its arguments are <code>TRUE</code>:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="data-types-part-1.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">&amp;</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Otherwise it returns <code>FALSE</code>:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="data-types-part-1.html#cb224-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">&amp;</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="data-types-part-1.html#cb226-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">&amp;</span> <span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="or-operator" class="section level5 hasAnchor" number="2.1.4.2.3">
<h5><span class="header-section-number">2.1.4.2.3</span> OR operator <code>|</code><a href="data-types-part-1.html#or-operator" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Binary operator OR (denoted <code>|</code>) returns <code>TRUE</code> result when <em>any</em> (at least one) of its arguments is <code>TRUE</code>:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="data-types-part-1.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">|</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="data-types-part-1.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">|</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Otherwise it returns <code>FALSE</code>:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="data-types-part-1.html#cb232-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">|</span> <span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
</div>
<div id="relational-operators" class="section level4 hasAnchor" number="2.1.4.3">
<h4><span class="header-section-number">2.1.4.3</span> Relational operators<a href="data-types-part-1.html#relational-operators" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="equality-operator" class="section level5 hasAnchor" number="2.1.4.3.1">
<h5><span class="header-section-number">2.1.4.3.1</span> Equality operator <code>==</code><a href="data-types-part-1.html#equality-operator" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="data-types-part-1.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">==</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="data-types-part-1.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Bioinformatics&quot;</span> <span class="sc">==</span> <span class="st">&quot;Biostatistics&quot;</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="data-types-part-1.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;biostatistics&quot;</span> <span class="sc">==</span> <span class="st">&quot;Biostatistics&quot;</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="data-types-part-1.html#cb240-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">==</span> F</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="inequality-operators" class="section level5 hasAnchor" number="2.1.4.3.2">
<h5><span class="header-section-number">2.1.4.3.2</span> Inequality operators<a href="data-types-part-1.html#inequality-operators" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Not equal:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="data-types-part-1.html#cb242-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">!=</span> <span class="dv">2</span>     </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="data-types-part-1.html#cb244-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;a&quot;</span> <span class="sc">!=</span> <span class="st">&quot;A&quot;</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="data-types-part-1.html#cb246-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">!=</span> T</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>As you can see, this can be used for numeric entries, character strings as well as logical values.</p>
<p>The operators “less than” (“&lt;”), greater than (“&gt;”) as well as their combinations with “equal” (“=”) are mostly used with numeric entries:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="data-types-part-1.html#cb248-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">&lt;</span> <span class="dv">2</span>     </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="data-types-part-1.html#cb250-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">&gt;</span> <span class="dv">2</span>     </span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="data-types-part-1.html#cb252-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">&lt;=</span> <span class="dv">2</span>    </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="data-types-part-1.html#cb254-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">&gt;=</span> <span class="dv">2</span>    </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
</div>
<div id="comparison-of-two-vectors" class="section level4 hasAnchor" number="2.1.4.4">
<h4><span class="header-section-number">2.1.4.4</span> Comparison of two vectors<a href="data-types-part-1.html#comparison-of-two-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="data-types-part-1.html#cb256-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span> )</span>
<span id="cb256-2"><a href="data-types-part-1.html#cb256-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span> )</span>
<span id="cb256-3"><a href="data-types-part-1.html#cb256-3" aria-hidden="true" tabindex="-1"></a>v <span class="sc">==</span> w</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="data-types-part-1.html#cb258-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">!=</span> w</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE  TRUE  TRUE</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="data-types-part-1.html#cb260-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">&lt;</span> w</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="data-types-part-1.html#cb262-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">&lt;=</span> w</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE  TRUE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="data-types-part-1.html#cb264-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">&gt;=</span> w</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE  TRUE</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/01_basic_data_types_cont.tasks.nocode.html#logical">the task(s)</a>, and check your solution(s) <a href="exercises/01_basic_data_types_cont.tasks.code.html#logical">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="type-conversions" class="section level3 hasAnchor" number="2.1.5">
<h3><span class="header-section-number">2.1.5</span> Type conversions<a href="data-types-part-1.html#type-conversions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sometimes a conversion to a vector of certain type might be needed.
The family of functions: <code>as.numeric()</code>, <code>as.character()</code>, <code>as.logical()</code> takes as an argument a vector of any type and returns a vector of the type given in the function name.
When the conversion of an element is not possible, an <code>NA</code> value is returned.</p>
<p>For example, a numeric vector can be converted into a character vector using <code>as.character()</code>:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="data-types-part-1.html#cb266-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span>
<span id="cb266-2"><a href="data-types-part-1.html#cb266-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="data-types-part-1.html#cb268-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.character</span>( v )</span></code></pre></div>
<pre><code>##  [1] &quot;101&quot; &quot;102&quot; &quot;103&quot; &quot;104&quot; &quot;105&quot; &quot;106&quot; &quot;107&quot; &quot;108&quot; &quot;109&quot; &quot;110&quot;</code></pre>
<p>Similarly, logical entries can be converted into numeric by using <code>as.numeric()</code>:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="data-types-part-1.html#cb270-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">TRUE</span>)</span>
<span id="cb270-2"><a href="data-types-part-1.html#cb270-2" aria-hidden="true" tabindex="-1"></a>l</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE  TRUE</code></pre>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="data-types-part-1.html#cb272-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(l)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="data-types-part-1.html#cb274-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(l)</span>
<span id="cb274-2"><a href="data-types-part-1.html#cb274-2" aria-hidden="true" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] 1 1 0 1</code></pre>
<p>Note that all entries equal to <code>TRUE</code> become <code>1</code>, and all equal to <code>FALSE</code> become <code>0</code>. If one entry is a string, the class of the entire vector changes:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="data-types-part-1.html#cb276-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="st">&quot;shoe&quot;</span>)</span>
<span id="cb276-2"><a href="data-types-part-1.html#cb276-2" aria-hidden="true" tabindex="-1"></a>l</span></code></pre></div>
<pre><code>## [1] &quot;TRUE&quot;  &quot;TRUE&quot;  &quot;FALSE&quot; &quot;shoe&quot;</code></pre>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="data-types-part-1.html#cb278-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(l)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Since a string cannot be transformed into numeric, all entries become <code>NA</code> in the result:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="data-types-part-1.html#cb280-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(l)</span></code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="data-types-part-1.html#cb282-1" aria-hidden="true" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] NA NA NA NA</code></pre>
<p>Type conversions must therefore be made carefully, by checking the class of the object to be converted.</p>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/01_basic_data_types_cont.tasks.nocode.html#conversions">the task(s)</a>, and check your solution(s) <a href="exercises/01_basic_data_types_cont.tasks.code.html#conversions">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="vectors-1" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Vectors<a href="data-types-part-1.html#vectors-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vectors are data structures which are able to store multiple elements in a defined order.</p>
<p>There are several ways to access (single/multiple) elements from vectors which are discussed below.</p>
<div id="square-brackets-operator" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Square brackets operator<a href="data-types-part-1.html#square-brackets-operator" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="by-numbers" class="section level4 hasAnchor" number="2.2.1.1">
<h4><span class="header-section-number">2.2.1.1</span> By numbers<a href="data-types-part-1.html#by-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Vector elements are kept at successive, numbered (indexed) positions.
R vectors keep the first element at index 1 and the last element at index which can be obtained with the function <code>length</code>.</p>
<p>The indices can be used to fetch elements from the corresponding positions with the square bracket operators <code>[ pos ]</code>.</p>
<p>Let us take a vector:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="data-types-part-1.html#cb284-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span></code></pre></div>
<p>To get the first element of <code>v</code>:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="data-types-part-1.html#cb285-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="dv">1</span> ]</span></code></pre></div>
<pre><code>## [1] 101</code></pre>
<p>To get the last element of <code>v</code>:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="data-types-part-1.html#cb287-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">length</span>( v ) ]</span></code></pre></div>
<pre><code>## [1] 110</code></pre>
<p>To get an element at a given index:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="data-types-part-1.html#cb289-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="dv">5</span> ]</span></code></pre></div>
<pre><code>## [1] 105</code></pre>
<p>Changing the value a single element:</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="data-types-part-1.html#cb291-1" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="data-types-part-1.html#cb293-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="dv">2</span> ] <span class="ot">&lt;-</span> <span class="dv">22</span></span>
<span id="cb293-2"><a href="data-types-part-1.html#cb293-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101  22 103 104 105 106 107 108 109 110</code></pre>
<p>Extracting multiple elements:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="data-types-part-1.html#cb295-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">7</span> ) ]</span></code></pre></div>
<pre><code>## [1]  22 104 107</code></pre>
<p>Changing the value of multiple elements:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="data-types-part-1.html#cb297-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">7</span> ) ] <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">22</span>, <span class="dv">24</span>, <span class="dv">27</span> )</span>
<span id="cb297-2"><a href="data-types-part-1.html#cb297-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101  22 103  24 105 106  27 108 109 110</code></pre>
</div>
<div id="by-names" class="section level4 hasAnchor" number="2.2.1.2">
<h4><span class="header-section-number">2.2.1.2</span> By names<a href="data-types-part-1.html#by-names" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Elements of the vectors can also be given names, creating a named vector. Let us take a vector:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="data-types-part-1.html#cb299-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span>
<span id="cb299-2"><a href="data-types-part-1.html#cb299-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<p>Setting names of vector elements:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="data-types-part-1.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( v ) <span class="ot">&lt;-</span> LETTERS[ <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>( v ) ]</span>
<span id="cb301-2"><a href="data-types-part-1.html#cb301-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##   A   B   C   D   E   F   G   H   I   J 
## 101 102 103 104 105 106 107 108 109 110</code></pre>
<p>Extracting names of vector elements:</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="data-types-part-1.html#cb303-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( v )</span></code></pre></div>
<pre><code>##  [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot; &quot;F&quot; &quot;G&quot; &quot;H&quot; &quot;I&quot; &quot;J&quot;</code></pre>
<p>Accessing elements (single or multiple) by names:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="data-types-part-1.html#cb305-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="st">&quot;C&quot;</span> ]</span></code></pre></div>
<pre><code>##   C 
## 103</code></pre>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="data-types-part-1.html#cb307-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">c</span>( <span class="st">&quot;F&quot;</span>, <span class="st">&quot;H&quot;</span> ) ]</span></code></pre></div>
<pre><code>##   F   H 
## 106 108</code></pre>
</div>
<div id="by-condition-logical-indices" class="section level4 hasAnchor" number="2.2.1.3">
<h4><span class="header-section-number">2.2.1.3</span> By condition (logical indices)<a href="data-types-part-1.html#by-condition-logical-indices" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can use a logical vector to select elements of a vector. Consider the vector</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="data-types-part-1.html#cb309-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">7</span>)</span></code></pre></div>
<p>and say that we want to select the second element, but not the first. For this we know we can use</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="data-types-part-1.html#cb310-1" aria-hidden="true" tabindex="-1"></a>b[ <span class="dv">2</span> ]</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>and it turns out we can also use a logical vector with <code>TRUE</code> for the element to be selected, and <code>FALSE</code> for the one not to be selected. That is <code>b[ c(FALSE, TRUE) ]</code> gives the same selection as above:</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="data-types-part-1.html#cb312-1" aria-hidden="true" tabindex="-1"></a>b[ <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">TRUE</span>) ]</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>Above we simply created the logical vector. It in fact could have been a result of another operation. For example, say that we have a vector representing the sex of the entries in <code>b</code>:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="data-types-part-1.html#cb314-1" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;female&quot;</span>, <span class="st">&quot;male&quot;</span>)</span></code></pre></div>
<p>To select the entry in <code>b</code> corresponding to <code>female</code>, we could create the logical vector indicating which entry is <code>female</code>:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="data-types-part-1.html#cb315-1" aria-hidden="true" tabindex="-1"></a>sex <span class="sc">==</span> <span class="st">&quot;female&quot;</span></span></code></pre></div>
<pre><code>## [1]  TRUE FALSE</code></pre>
<p>Now we use this to select the desired entry in <code>b</code>:</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="data-types-part-1.html#cb317-1" aria-hidden="true" tabindex="-1"></a>b[ sex <span class="sc">==</span> <span class="st">&quot;female&quot;</span> ]</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>Let us now take a longer vector:</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="data-types-part-1.html#cb319-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span>
<span id="cb319-2"><a href="data-types-part-1.html#cb319-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<p>Construct a second vector <code>u</code> of the same length:</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="data-types-part-1.html#cb321-1" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">:</span><span class="dv">1</span></span></code></pre></div>
<p>We want to select all entries in <code>v</code> for which <code>u &gt; 5</code>. We will now create a
<code>idx</code> with the result of the operation <code>u &gt; 5</code>:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="data-types-part-1.html#cb322-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> u <span class="sc">&gt;</span> <span class="dv">5</span></span></code></pre></div>
<p>Now we can select entries in <code>v</code> by using <code>idx</code>: entries are selected or not according to:</p>
<ul>
<li><code>TRUE</code> in <code>idx</code>, then the element appears in the result;</li>
<li><code>FALSE</code> in <code>idx</code>, then the element is skipped;</li>
</ul>
<p>A logical vector like <code>idx</code> is typically a result of equality/comparison, as above, or is generated by specialized functions. For example, if we wish to select entries in <code>v</code> that have values at least equal to 102 and smaller than 106, we could use:</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="data-types-part-1.html#cb323-1" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="data-types-part-1.html#cb325-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> v <span class="sc">&gt;=</span> <span class="dv">102</span></span>
<span id="cb325-2"><a href="data-types-part-1.html#cb325-2" aria-hidden="true" tabindex="-1"></a>idx</span></code></pre></div>
<pre><code>##  [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="data-types-part-1.html#cb327-1" aria-hidden="true" tabindex="-1"></a>v[ idx ]</span></code></pre></div>
<pre><code>## [1] 102 103 104 105 106 107 108 109 110</code></pre>
<p>We can also combine logical statements into a single one. Say, if we wish to select entries in <code>v</code> that have values at least equal to 102 and smaller than 106, we could use:</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="data-types-part-1.html#cb329-1" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="data-types-part-1.html#cb331-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> (v <span class="sc">&gt;=</span> <span class="dv">102</span>) <span class="sc">&amp;</span> (v <span class="sc">&lt;</span> <span class="dv">106</span>)</span>
<span id="cb331-2"><a href="data-types-part-1.html#cb331-2" aria-hidden="true" tabindex="-1"></a>idx</span></code></pre></div>
<pre><code>##  [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="data-types-part-1.html#cb333-1" aria-hidden="true" tabindex="-1"></a>v[ idx ]</span></code></pre></div>
<pre><code>## [1] 102 103 104 105</code></pre>
<p>Indices given by a logical vector are referred to as <em>logical indices</em>.</p>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/02_selecting.tasks.nocode.html#brackets">the task(s)</a>, and check your solution(s) <a href="exercises/02_selecting.tasks.code.html#brackets">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="class-of-a-vector" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> (*) Class of a vector<a href="data-types-part-1.html#class-of-a-vector" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A vector is essentially a combination of entries all of the same class. When entries given are of different classes, the simplest class is chosen and assigned for all entries. This class then gives the class of the vector.</p>
<p>In the section about conversions, we had a vector with mostly logical entries, but for one entry which was character, and the class of the entire vector became <code>character</code>:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="data-types-part-1.html#cb335-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="st">&quot;shoe&quot;</span>)</span>
<span id="cb335-2"><a href="data-types-part-1.html#cb335-2" aria-hidden="true" tabindex="-1"></a>l</span></code></pre></div>
<pre><code>## [1] &quot;TRUE&quot;  &quot;TRUE&quot;  &quot;FALSE&quot; &quot;shoe&quot;</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="data-types-part-1.html#cb337-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(l)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>This happened because the function <code>c()</code> looks for the simplest class of all entries in <code>l</code>, and <code>character</code> is simpler than <code>logical</code>. Similarly, a vector defined as:</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="data-types-part-1.html#cb339-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">1</span>, <span class="st">&quot;hand&quot;</span>)</span>
<span id="cb339-2"><a href="data-types-part-1.html#cb339-2" aria-hidden="true" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] &quot;5&quot;    &quot;4&quot;    &quot;3&quot;    &quot;2&quot;    &quot;1&quot;    &quot;hand&quot;</code></pre>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="data-types-part-1.html#cb341-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(n)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>is of class <code>character</code>, which is simpler than <code>numeric</code>, the class of almost all original entries in <code>n</code>.</p>
<p>The rough order of classes is: <code>logical</code> &lt; <code>integer</code> &lt; <code>numeric</code> &lt; <code>complex</code> &lt; <code>character</code> &lt; <code>list</code> (we will see lists later). For now, it suffices to see that <code>character</code> is one of the simplest classes, which explains why in the examples above the resulting vector was of that class.</p>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/02_selecting.tasks.nocode.html#vectorClass">the task(s)</a>, and check your solution(s) <a href="exercises/02_selecting.tasks.code.html#vectorClass">here</a>.</p>
</blockquote>
<hr />
</div>
<div id="other-useful-functions" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Other useful functions<a href="data-types-part-1.html#other-useful-functions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Other useful functions are:</p>
<ul>
<li><code>sort()</code>: sorts the elements of a vector:</li>
</ul>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="data-types-part-1.html#cb343-1" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="data-types-part-1.html#cb345-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(v)</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<ul>
<li><code>unique()</code>: returns a vector containing the unique entries of a vector:</li>
</ul>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="data-types-part-1.html#cb347-1" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb347-2"><a href="data-types-part-1.html#cb347-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(u)</span></code></pre></div>
<pre><code>## [1] 5 4 3 1</code></pre>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="data-types-part-1.html#cb349-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Monday&quot;</span>, <span class="st">&quot;Tuesday&quot;</span>, <span class="st">&quot;Thursday&quot;</span>, <span class="st">&quot;Friday&quot;</span>, <span class="st">&quot;Monday&quot;</span>, <span class="st">&quot;Wednesday&quot;</span>, <span class="st">&quot;Thursday&quot;</span>)</span>
<span id="cb349-2"><a href="data-types-part-1.html#cb349-2" aria-hidden="true" tabindex="-1"></a>w</span></code></pre></div>
<pre><code>## [1] &quot;Monday&quot;    &quot;Tuesday&quot;   &quot;Thursday&quot;  &quot;Friday&quot;    &quot;Monday&quot;    &quot;Wednesday&quot;
## [7] &quot;Thursday&quot;</code></pre>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="data-types-part-1.html#cb351-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(w)</span></code></pre></div>
<pre><code>## [1] &quot;Monday&quot;    &quot;Tuesday&quot;   &quot;Thursday&quot;  &quot;Friday&quot;    &quot;Wednesday&quot;</code></pre>
<ul>
<li><code>duplicated()</code>: returns a logical vector indicating which entries are duplicated or not:</li>
</ul>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="data-types-part-1.html#cb353-1" aria-hidden="true" tabindex="-1"></a><span class="fu">duplicated</span>(u)</span></code></pre></div>
<pre><code>## [1] FALSE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="data-types-part-1.html#cb355-1" aria-hidden="true" tabindex="-1"></a><span class="fu">duplicated</span>(w)</span></code></pre></div>
<pre><code>## [1] FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE</code></pre>
<p>So, in order to select all duplicated entries, the following could be used:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="data-types-part-1.html#cb357-1" aria-hidden="true" tabindex="-1"></a>u[ <span class="fu">duplicated</span>(u) ]</span></code></pre></div>
<pre><code>## [1] 5 4</code></pre>
<p>If instead you wish to select all unique entries, you can use:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="data-types-part-1.html#cb359-1" aria-hidden="true" tabindex="-1"></a>u[ <span class="sc">!</span><span class="fu">duplicated</span>(u) ]</span></code></pre></div>
<pre><code>## [1] 5 4 3 1</code></pre>
<p>You can check that this is the same result that you get using <code>unique()</code>:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="data-types-part-1.html#cb361-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(u)</span></code></pre></div>
<pre><code>## [1] 5 4 3 1</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/02_selecting.tasks.nocode.html#utility">the task(s)</a>, and check your solution(s) <a href="exercises/02_selecting.tasks.code.html#utility">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="data-frames" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Data frames<a href="data-types-part-1.html#data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="what-is-a-data-frame" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> What is a data frame?<a href="data-types-part-1.html#what-is-a-data-frame" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<center>
<div class="figure">
<img src="figure/Data_types_mdfl.png" alt="" />
<p class="caption">Vectors</p>
</div>
</center>
<p>A data frame is a collection of variables represented as vectors of the same length.</p>
<p>Therefore, all the vectors (columns) should have unique names. They can be of different types: one column can be character, another a factor, and other columns can be numeric. Of course, entries within a single vector are all of the same type.</p>
<p>Rows represent separate records/individuals/samples.</p>
<p>Rows may have names as well (although for new code, better create a separate column with names).</p>
</div>
<div id="creating-a-data-frame" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Creating a data frame<a href="data-types-part-1.html#creating-a-data-frame" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="from-manually-provided-vectors" class="section level4 hasAnchor" number="2.3.2.1">
<h4><span class="header-section-number">2.3.2.1</span> From manually provided vectors<a href="data-types-part-1.html#from-manually-provided-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>An example data frame built of <code>character</code>, <code>numeric</code> and <code>logical</code> vectors:</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="data-types-part-1.html#cb363-1" aria-hidden="true" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;E&quot;</span> );</span>
<span id="cb363-2"><a href="data-types-part-1.html#cb363-2" aria-hidden="true" tabindex="-1"></a>ns <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;Amy&quot;</span>, <span class="st">&quot;Bob&quot;</span>, <span class="st">&quot;Dan&quot;</span>, <span class="st">&quot;Eve&quot;</span> )</span>
<span id="cb363-3"><a href="data-types-part-1.html#cb363-3" aria-hidden="true" tabindex="-1"></a>as <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">40</span>, <span class="cn">NA</span>, <span class="dv">6</span>, <span class="dv">16</span> )</span>
<span id="cb363-4"><a href="data-types-part-1.html#cb363-4" aria-hidden="true" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="cn">TRUE</span>, <span class="cn">NA</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span> )</span>
<span id="cb363-5"><a href="data-types-part-1.html#cb363-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb363-6"><a href="data-types-part-1.html#cb363-6" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb363-7"><a href="data-types-part-1.html#cb363-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> ids,</span>
<span id="cb363-8"><a href="data-types-part-1.html#cb363-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> ns,</span>
<span id="cb363-9"><a href="data-types-part-1.html#cb363-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> as,</span>
<span id="cb363-10"><a href="data-types-part-1.html#cb363-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">smoker =</span> ss</span>
<span id="cb363-11"><a href="data-types-part-1.html#cb363-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb363-12"><a href="data-types-part-1.html#cb363-12" aria-hidden="true" tabindex="-1"></a>d</span></code></pre></div>
<pre><code>##   name age smoker
## A  Amy  40   TRUE
## B  Bob  NA     NA
## D  Dan   6  FALSE
## E  Eve  16  FALSE</code></pre>
<p>The class of <code>d</code> is:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="data-types-part-1.html#cb365-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( d )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>The function <code>str()</code> gives a compact display of an object structure/content. For a data frame, this includes the class (<code>data frame</code>), dimensions (numbers of rows and columns), column names as well as their classes:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="data-types-part-1.html#cb367-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    4 obs. of  3 variables:
##  $ name  : chr  &quot;Amy&quot; &quot;Bob&quot; &quot;Dan&quot; &quot;Eve&quot;
##  $ age   : num  40 NA 6 16
##  $ smoker: logi  TRUE NA FALSE FALSE</code></pre>
</div>
<div id="from-imported-files" class="section level4 hasAnchor" number="2.3.2.2">
<h4><span class="header-section-number">2.3.2.2</span> From imported files<a href="data-types-part-1.html#from-imported-files" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Datasets my come in various formats, e.g. <code>.tsv</code>, <code>.csv</code>, <code>.xls(x)</code>, <code>.sav</code>, <code>.txt</code> etc. R provides functions to import these formats, which are then considered as data frames.</p>
<p><em>Note</em>: after importing a file, always check the columns read, as well as whether their classes and values are as expected. Additional conversions might be necessary (e.g. declaring factor levels, order of factor levels).</p>
<div id="tsv-file" class="section level5 hasAnchor" number="2.3.2.2.1">
<h5><span class="header-section-number">2.3.2.2.1</span> TSV file<a href="data-types-part-1.html#tsv-file" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>For files stored in <a href="https://en.wikipedia.org/wiki/Tab-separated_values">tab-separated files (<code>tsv</code>) format</a> use:</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="data-types-part-1.html#cb369-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.table</span>( <span class="st">&quot;data/pulse.tsv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span> )</span></code></pre></div>
<pre><code># To get &#39;pulse.tsv&#39; directly from the server, use:
# d &lt;- read.table( url( &quot;/tree/master/data/pulse.tsv&quot; ), header = TRUE, sep = &quot;\t&quot; )</code></pre>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="data-types-part-1.html#cb371-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    110 obs. of  12 variables:
##  $ name    : chr  &quot;Bonnie&quot; &quot;Melanie&quot; &quot;Consuelo&quot; &quot;Travis&quot; ...
##  $ height  : int  173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num  57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : int  18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : chr  &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...
##  $ smokes  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ alcohol : chr  &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ exercise: chr  &quot;moderate&quot; &quot;moderate&quot; &quot;high&quot; &quot;high&quot; ...
##  $ ran     : chr  &quot;sat&quot; &quot;ran&quot; &quot;ran&quot; &quot;sat&quot; ...
##  $ pulse1  : int  86 82 96 71 90 78 68 71 68 88 ...
##  $ pulse2  : int  88 150 176 73 88 141 72 77 68 150 ...
##  $ year    : int  1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 ...</code></pre>
</div>
<div id="csv-file" class="section level5 hasAnchor" number="2.3.2.2.2">
<h5><span class="header-section-number">2.3.2.2.2</span> CSV file<a href="data-types-part-1.html#csv-file" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Data frames (tables) stored in files in <a href="https://en.wikipedia.org/wiki/Comma-separated_values">comma-separated values (<code>csv</code>) format</a> can be read with:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="data-types-part-1.html#cb373-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">&quot;data/pulse.csv&quot;</span> );</span></code></pre></div>
<pre><code># To get &#39;pulse.csv&#39; directly from the server, use:
# d &lt;- read.csv( url( &quot;/tree/master/data/pulse.csv&quot; ) )</code></pre>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="data-types-part-1.html#cb375-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    110 obs. of  13 variables:
##  $ id      : chr  &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; ...
##  $ name    : chr  &quot;Bonnie&quot; &quot;Melanie&quot; &quot;Consuelo&quot; &quot;Travis&quot; ...
##  $ height  : int  173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num  57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : int  18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : chr  &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...
##  $ smokes  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ alcohol : chr  &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ exercise: chr  &quot;moderate&quot; &quot;moderate&quot; &quot;high&quot; &quot;high&quot; ...
##  $ ran     : chr  &quot;sat&quot; &quot;ran&quot; &quot;ran&quot; &quot;sat&quot; ...
##  $ pulse1  : int  86 82 96 71 90 78 68 71 68 88 ...
##  $ pulse2  : int  88 150 176 73 88 141 72 77 68 150 ...
##  $ year    : int  1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 ...</code></pre>
</div>
<div id="microsoft-excel-file" class="section level5 hasAnchor" number="2.3.2.2.3">
<h5><span class="header-section-number">2.3.2.2.3</span> (*) Microsoft Excel file<a href="data-types-part-1.html#microsoft-excel-file" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Reading Microsoft Excel files requires an additional library/package, which needs to be installed first. There exists several packages providing reading of Excel files.</p>
<div id="with-package-readxl" class="section level6 hasAnchor" number="2.3.2.2.3.1">
<h6><span class="header-section-number">2.3.2.2.3.1</span> (*) With package readxl<a href="data-types-part-1.html#with-package-readxl" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="data-types-part-1.html#cb377-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages( &quot;readxl&quot; )</span></span>
<span id="cb377-2"><a href="data-types-part-1.html#cb377-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( readxl );</span>
<span id="cb377-3"><a href="data-types-part-1.html#cb377-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_excel</span>( <span class="st">&quot;data/pulse.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="dv">1</span> );</span>
<span id="cb377-4"><a href="data-types-part-1.html#cb377-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d );</span></code></pre></div>
<pre><code>## tibble [110 × 13] (S3: tbl_df/tbl/data.frame)
##  $ id      : chr [1:110] &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; ...
##  $ name    : chr [1:110] &quot;Bonnie&quot; &quot;Melanie&quot; &quot;Consuelo&quot; &quot;Travis&quot; ...
##  $ height  : num [1:110] 173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num [1:110] 57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : num [1:110] 18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : chr [1:110] &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...
##  $ smokes  : chr [1:110] &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ alcohol : chr [1:110] &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ exercise: chr [1:110] &quot;moderate&quot; &quot;moderate&quot; &quot;high&quot; &quot;high&quot; ...
##  $ ran     : chr [1:110] &quot;sat&quot; &quot;ran&quot; &quot;ran&quot; &quot;sat&quot; ...
##  $ pulse1  : chr [1:110] &quot;86&quot; &quot;82&quot; &quot;96&quot; &quot;71&quot; ...
##  $ pulse2  : chr [1:110] &quot;88&quot; &quot;150&quot; &quot;176&quot; &quot;73&quot; ...
##  $ year    : num [1:110] 1993 1993 1993 1993 1993 ...</code></pre>
</div>
<div id="with-package-gdata" class="section level6 hasAnchor" number="2.3.2.2.3.2">
<h6><span class="header-section-number">2.3.2.2.3.2</span> (*) With package gdata<a href="data-types-part-1.html#with-package-gdata" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<p>Please note that the <code>gdata</code> package requires additional PERL packages to be installed; <code>readxl</code> seems to be easier to use.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="data-types-part-1.html#cb379-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages( &quot;gdata&quot; )</span></span>
<span id="cb379-2"><a href="data-types-part-1.html#cb379-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( gdata )</span>
<span id="cb379-3"><a href="data-types-part-1.html#cb379-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.xls</span>( <span class="st">&quot;data/pulse.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="dv">1</span> )</span>
<span id="cb379-4"><a href="data-types-part-1.html#cb379-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
</div>
</div>
</div>
<div id="spss-files" class="section level4 hasAnchor" number="2.3.2.3">
<h4><span class="header-section-number">2.3.2.3</span> (*) SPSS files<a href="data-types-part-1.html#spss-files" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Reading SPSS files requires the additional library/package <code>foreign</code> (normally installed with R distribution).</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="data-types-part-1.html#cb380-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( foreign )</span>
<span id="cb380-2"><a href="data-types-part-1.html#cb380-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.spss</span>( <span class="st">&quot;data/pulse.sav&quot;</span>, <span class="at">to.data.frame =</span> <span class="cn">TRUE</span> )</span>
<span id="cb380-3"><a href="data-types-part-1.html#cb380-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    110 obs. of  13 variables:
##  $ id      : chr  &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; ...
##  $ name    : chr  &quot;Bonnie     &quot; &quot;Melanie    &quot; &quot;Consuelo   &quot; &quot;Travis     &quot; ...
##  $ height  : num  173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num  57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : num  18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 1 1 1 2 1 2 1 1 1 2 ...
##  $ smokes  : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ alcohol : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ exercise: Factor w/ 3 levels &quot;low&quot;,&quot;moderate&quot;,..: 2 2 3 3 1 1 2 2 3 2 ...
##  $ ran     : Factor w/ 2 levels &quot;sat&quot;,&quot;ran&quot;: 1 2 2 1 1 2 1 1 1 2 ...
##  $ pulse1  : num  86 82 96 71 90 78 68 71 68 88 ...
##  $ pulse2  : num  88 150 176 73 88 141 72 77 68 150 ...
##  $ year    : Factor w/ 5 levels &quot;1993&quot;,&quot;1995&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  - attr(*, &quot;codepage&quot;)= int 65001</code></pre>
</div>
</div>
<div id="properties" class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Properties<a href="data-types-part-1.html#properties" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let us discuss the data frame <code>pulse</code>:</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="data-types-part-1.html#cb382-1" aria-hidden="true" tabindex="-1"></a>pulse <span class="ot">&lt;-</span> <span class="fu">read.table</span>( <span class="st">&quot;data/pulse.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span> )</span></code></pre></div>
<pre><code># To get &#39;pulse.txt&#39; directly from the server, use:
# pulse &lt;- read.table( url( &quot;/tree/master/data/pulse.txt&quot; ), header = TRUE, sep = &quot;\t&quot; )</code></pre>
<p>To shorten output we will use the first 20 rows of the <code>pulse</code> data frame:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="data-types-part-1.html#cb384-1" aria-hidden="true" tabindex="-1"></a>pulse <span class="ot">&lt;-</span> <span class="fu">head</span>( pulse, <span class="dv">20</span> )</span></code></pre></div>
<div id="dimensions-1" class="section level4 hasAnchor" number="2.3.3.1">
<h4><span class="header-section-number">2.3.3.1</span> Dimensions<a href="data-types-part-1.html#dimensions-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There are several functions to get dimensions of a data frame:</p>
<ul>
<li><code>ncol( pulse )</code> provides the number of columns:</li>
</ul>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="data-types-part-1.html#cb385-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>( pulse )</span></code></pre></div>
<pre><code>## [1] 12</code></pre>
<ul>
<li><code>nrow( pulse )</code> provides the number of rows:</li>
</ul>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="data-types-part-1.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>( pulse )</span></code></pre></div>
<pre><code>## [1] 20</code></pre>
<ul>
<li><code>dim( pulse )</code> returns a vector with two elements: number of rows and number of columns</li>
</ul>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="data-types-part-1.html#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>( pulse )</span></code></pre></div>
<pre><code>## [1] 20 12</code></pre>
</div>
<div id="columnsrows-names" class="section level4 hasAnchor" number="2.3.3.2">
<h4><span class="header-section-number">2.3.3.2</span> Columns/rows names<a href="data-types-part-1.html#columnsrows-names" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><code>colnames()</code> is used to get the names of the columns. In data frames, the same result is returned by <code>names()</code>:</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="data-types-part-1.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( pulse )</span></code></pre></div>
<pre><code>##  [1] &quot;name&quot;     &quot;height&quot;   &quot;weight&quot;   &quot;age&quot;      &quot;gender&quot;   &quot;smokes&quot;  
##  [7] &quot;alcohol&quot;  &quot;exercise&quot; &quot;ran&quot;      &quot;pulse1&quot;   &quot;pulse2&quot;   &quot;year&quot;</code></pre>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="data-types-part-1.html#cb393-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( pulse )</span></code></pre></div>
<pre><code>##  [1] &quot;name&quot;     &quot;height&quot;   &quot;weight&quot;   &quot;age&quot;      &quot;gender&quot;   &quot;smokes&quot;  
##  [7] &quot;alcohol&quot;  &quot;exercise&quot; &quot;ran&quot;      &quot;pulse1&quot;   &quot;pulse2&quot;   &quot;year&quot;</code></pre>
<p>To get names of the rows use:</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="data-types-part-1.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( pulse )</span></code></pre></div>
<pre><code>##  [1] &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; &quot;1993_E&quot; &quot;1993_F&quot; &quot;1993_G&quot; &quot;1993_H&quot;
##  [9] &quot;1993_I&quot; &quot;1993_J&quot; &quot;1993_K&quot; &quot;1993_L&quot; &quot;1993_M&quot; &quot;1993_N&quot; &quot;1993_O&quot; &quot;1993_P&quot;
## [17] &quot;1993_Q&quot; &quot;1993_R&quot; &quot;1993_S&quot; &quot;1993_T&quot;</code></pre>
</div>
</div>
<div id="content" class="section level3 hasAnchor" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Content<a href="data-types-part-1.html#content" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A column of a data frame might be accessed through the <code>$</code> operator.</p>
<p>Additionally, the content of a data frame can be accessed with the square bracket <code>[ ]</code> (square brackets) operator used in two different ways:</p>
<ul>
<li>with one argument <code>[ col(s) ]</code> referring to a column</li>
<li>with two arguments <code>[ row(s), col(s) ]</code></li>
</ul>
<!-- Note:  sometimes it is not obvious what is returned by those operators.
When a single column is requested, should it be:

- a vector with the column elements (so, a 1-dimensional structure)?
- a data frame with a single column (so, a 2-dimensional structure)? -->
<p>We can illustrate this by creating a vector with the <code>height</code> variable of the <code>pulse</code> data, using both syntaxes:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="data-types-part-1.html#cb397-1" aria-hidden="true" tabindex="-1"></a>height1 <span class="ot">&lt;-</span> pulse[ <span class="st">&quot;height&quot;</span> ]</span>
<span id="cb397-2"><a href="data-types-part-1.html#cb397-2" aria-hidden="true" tabindex="-1"></a>height2 <span class="ot">&lt;-</span> pulse[, <span class="st">&quot;height&quot;</span> ]</span></code></pre></div>
<p>Now check the class of the objects created:</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="data-types-part-1.html#cb398-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(height1) </span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="data-types-part-1.html#cb400-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(height2) </span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>So, by extracting one column of <code>pulse</code> using the syntax <code>[, columnName]</code>, a vector is created. However, if the comma is omitted, the result is of class <code>data.frame</code>.</p>
<div id="dollar-operator" class="section level4 hasAnchor" number="2.3.4.1">
<h4><span class="header-section-number">2.3.4.1</span> Dollar operator<a href="data-types-part-1.html#dollar-operator" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>$</code> method returns a <em>single</em> column as a <em>vector</em>:</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="data-types-part-1.html#cb402-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="sc">$</span>weight</span></code></pre></div>
<pre><code>##  [1]  57  58  62  84  64  74  57  55  56  60  75  58  68  59  72 110  56  70  56
## [20]  50</code></pre>
<p>When the column name is valid the returned value is a <em>vector</em>:</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="data-types-part-1.html#cb404-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse<span class="sc">$</span>weight )</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>When the name is invalid, <code>NULL</code> is returned:</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="data-types-part-1.html#cb406-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="sc">$</span>wrong</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>Be careful: the <code>$</code> notation searches for a column name starting with a provided prefix:</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="data-types-part-1.html#cb408-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="sc">$</span>we</span></code></pre></div>
<pre><code>##  [1]  57  58  62  84  64  74  57  55  56  60  75  58  68  59  72 110  56  70  56
## [20]  50</code></pre>
</div>
<div id="square-brackets-operator-single-argument" class="section level4 hasAnchor" number="2.3.4.2">
<h4><span class="header-section-number">2.3.4.2</span> Square brackets operator, single argument<a href="data-types-part-1.html#square-brackets-operator-single-argument" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Square brackets notation with a single argument return requested columns as a <code>data.frame</code> (compare to the dollar operator section):</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="data-types-part-1.html#cb410-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="st">&#39;weight&#39;</span> ]</span></code></pre></div>
<pre><code>##        weight
## 1993_A     57
## 1993_B     58
## 1993_C     62
## 1993_D     84
## 1993_E     64
## 1993_F     74
## 1993_G     57
## 1993_H     55
## 1993_I     56
## 1993_J     60
## 1993_K     75
## 1993_L     58
## 1993_M     68
## 1993_N     59
## 1993_O     72
## 1993_P    110
## 1993_Q     56
## 1993_R     70
## 1993_S     56
## 1993_T     50</code></pre>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="data-types-part-1.html#cb412-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ <span class="st">&#39;weight&#39;</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="data-types-part-1.html#cb414-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="dv">3</span> ]</span></code></pre></div>
<pre><code>##        weight
## 1993_A     57
## 1993_B     58
## 1993_C     62
## 1993_D     84
## 1993_E     64
## 1993_F     74
## 1993_G     57
## 1993_H     55
## 1993_I     56
## 1993_J     60
## 1993_K     75
## 1993_L     58
## 1993_M     68
## 1993_N     59
## 1993_O     72
## 1993_P    110
## 1993_Q     56
## 1993_R     70
## 1993_S     56
## 1993_T     50</code></pre>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="data-types-part-1.html#cb416-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ <span class="dv">3</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Since the returned object is a <code>data.frame</code>, multiple columns might be returned (for example in a different order than they are in the <code>pulse</code> data):</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="data-types-part-1.html#cb418-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_B    179     58
## 1993_C    167     62
## 1993_D    195     84
## 1993_E    173     64
## 1993_F    184     74
## 1993_G    162     57
## 1993_H    169     55
## 1993_I    164     56
## 1993_J    168     60
## 1993_K    170     75
## 1993_L    178     58
## 1993_M    170     68
## 1993_N    187     59
## 1993_O    180     72
## 1993_P    185    110
## 1993_Q    170     56
## 1993_R    180     70
## 1993_S    166     56
## 1993_T    155     50</code></pre>
<p>When a name is invalid, an error is produced:</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="data-types-part-1.html#cb420-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="st">&#39;wrong&#39;</span> ]</span></code></pre></div>
<pre><code>## Error in `[.data.frame`(pulse, &quot;wrong&quot;): undefined columns selected</code></pre>
</div>
<div id="square-brackets-operator-two-arguments" class="section level4 hasAnchor" number="2.3.4.3">
<h4><span class="header-section-number">2.3.4.3</span> Square brackets operator, two arguments<a href="data-types-part-1.html#square-brackets-operator-two-arguments" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The single brackets notation with two arguments <code>[ row(s), col(s) ]</code> separated by a comma can be used to get (multiple) row(s) and (multiple) column(s):</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="data-types-part-1.html#cb422-1" aria-hidden="true" tabindex="-1"></a>pulse[<span class="dv">2</span>, <span class="st">&quot;weight&quot;</span>]</span></code></pre></div>
<pre><code>## [1] 58</code></pre>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="data-types-part-1.html#cb424-1" aria-hidden="true" tabindex="-1"></a>pulse[<span class="st">&quot;1993_C&quot;</span>, <span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 62</code></pre>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="data-types-part-1.html#cb426-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="dv">1</span>, <span class="dv">3</span> ), <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_C    167     62</code></pre>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="data-types-part-1.html#cb428-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="st">&quot;1993_C&quot;</span>, <span class="st">&quot;1993_A&quot;</span>, <span class="st">&quot;wrong&quot;</span> ), <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_C    167     62
## 1993_A    173     57
## NA         NA     NA</code></pre>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="data-types-part-1.html#cb430-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="dv">4</span><span class="sc">:</span><span class="dv">8</span>, <span class="st">&quot;smokes&quot;</span>]</span></code></pre></div>
<pre><code>## [1] &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot;</code></pre>
<p>Note the class of the output when extracting multiple columns:</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="data-types-part-1.html#cb432-1" aria-hidden="true" tabindex="-1"></a>pulse[ , <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_B    179     58
## 1993_C    167     62
## 1993_D    195     84
## 1993_E    173     64
## 1993_F    184     74
## 1993_G    162     57
## 1993_H    169     55
## 1993_I    164     56
## 1993_J    168     60
## 1993_K    170     75
## 1993_L    178     58
## 1993_M    170     68
## 1993_N    187     59
## 1993_O    180     72
## 1993_P    185    110
## 1993_Q    170     56
## 1993_R    180     70
## 1993_S    166     56
## 1993_T    155     50</code></pre>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="data-types-part-1.html#cb434-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ , <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ] )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>And now extracting a single column:</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="data-types-part-1.html#cb436-1" aria-hidden="true" tabindex="-1"></a>pulse[ , <span class="fu">c</span>( <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##  [1]  57  58  62  84  64  74  57  55  56  60  75  58  68  59  72 110  56  70  56
## [20]  50</code></pre>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="data-types-part-1.html#cb438-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ , <span class="fu">c</span>( <span class="st">&#39;weight&#39;</span> ) ] )</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>Within the square bracket, an empty index field refers to all rows or columns:</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="data-types-part-1.html#cb440-1" aria-hidden="true" tabindex="-1"></a>pulse[ , ]</span></code></pre></div>
<pre><code>##             name height weight age gender smokes alcohol exercise ran pulse1
## 1993_A    Bonnie    173     57  18 female     no     yes moderate sat     86
## 1993_B   Melanie    179     58  19 female     no     yes moderate ran     82
## 1993_C  Consuelo    167     62  18 female     no     yes     high ran     96
## 1993_D    Travis    195     84  18   male     no     yes     high sat     71
## 1993_E     Lauri    173     64  18 female     no     yes      low sat     90
## 1993_F    George    184     74  22   male     no     yes      low ran     78
## 1993_G    Cherry    162     57  20 female     no     yes moderate sat     68
## 1993_H Francesca    169     55  18 female     no     yes moderate sat     71
## 1993_I     Sonja    164     56  19 female     no     yes     high sat     68
## 1993_J      Troy    168     60  23   male     no     yes moderate ran     88
## 1993_K    Roland    170     75  20   male     no     yes     high ran     76
## 1993_L Frederick    178     58  19   male     no      no      low sat     74
## 1993_M    Justin    170     68  22   male    yes     yes moderate sat     70
## 1993_N    Ernest    187     59  18   male     no     yes     high sat     78
## 1993_O  Salvador    180     72  18   male     no     yes moderate sat     69
## 1993_P    Mathew    185    110  22   male     no     yes      low sat     77
## 1993_Q    Leslie    170     56  19   male     no      no      low sat     64
## 1993_R   Raymond    180     70  18   male     no     yes moderate ran     80
## 1993_S    Nicole    166     56  21 female    yes      no moderate sat     83
## 1993_T     Maura    155     50  19 female     no      no moderate sat     78
##        pulse2 year
## 1993_A     88 1993
## 1993_B    150 1993
## 1993_C    176 1993
## 1993_D     73 1993
## 1993_E     88 1993
## 1993_F    141 1993
## 1993_G     72 1993
## 1993_H     77 1993
## 1993_I     68 1993
## 1993_J    150 1993
## 1993_K     88 1993
## 1993_L     76 1993
## 1993_M     71 1993
## 1993_N     82 1993
## 1993_O     67 1993
## 1993_P     73 1993
## 1993_Q     63 1993
## 1993_R    146 1993
## 1993_S     79 1993
## 1993_T     79 1993</code></pre>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="data-types-part-1.html#cb442-1" aria-hidden="true" tabindex="-1"></a>pulse[ , <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_B    179     58
## 1993_C    167     62
## 1993_D    195     84
## 1993_E    173     64
## 1993_F    184     74
## 1993_G    162     57
## 1993_H    169     55
## 1993_I    164     56
## 1993_J    168     60
## 1993_K    170     75
## 1993_L    178     58
## 1993_M    170     68
## 1993_N    187     59
## 1993_O    180     72
## 1993_P    185    110
## 1993_Q    170     56
## 1993_R    180     70
## 1993_S    166     56
## 1993_T    155     50</code></pre>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="data-types-part-1.html#cb444-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="st">&quot;1993_C&quot;</span>, <span class="st">&quot;1993_A&quot;</span> ), ]</span></code></pre></div>
<pre><code>##            name height weight age gender smokes alcohol exercise ran pulse1
## 1993_C Consuelo    167     62  18 female     no     yes     high ran     96
## 1993_A   Bonnie    173     57  18 female     no     yes moderate sat     86
##        pulse2 year
## 1993_C    176 1993
## 1993_A     88 1993</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/03_data_frames.tasks.nocode.html#dataframes">the task(s)</a>, and check your solution(s) <a href="exercises/03_data_frames.tasks.code.html#dataframes">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
</div>
<div id="matrices" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Matrices<a href="data-types-part-1.html#matrices" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="what-is-a-matrix" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> What is a matrix<a href="data-types-part-1.html#what-is-a-matrix" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<center>
<div class="figure">
<img src="figure/Data_types_mdfl.png" alt="" />
<p class="caption">Vectors</p>
</div>
</center>
<p>A matrix is a two-dimensional array of elements of the same type. It can be seen as a generalization of a vector, with all entries are of the same type, only now with rows and columns. Conversely, a vector can be seen as a matrix of a single row or a single column (depending on the case).</p>
<p>Similar to data frames, rows and columns are addressed by numerical indices.
Rows and columns can also be named and be used for indexing.</p>
<p>Many of the functions used for a <code>data.frame</code> to assess elements can be used for matrices as well, as we will see.</p>
</div>
<div id="creation" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Creation<a href="data-types-part-1.html#creation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A matrix can be constructed from a vector by using the function <code>matrix()</code>. Depending on the arguments, elements are put to the matrix in a different order:</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="data-types-part-1.html#cb446-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">nrow =</span> <span class="dv">2</span> )</span>
<span id="cb446-2"><a href="data-types-part-1.html#cb446-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="data-types-part-1.html#cb448-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span> )</span>
<span id="cb448-2"><a href="data-types-part-1.html#cb448-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    3
## [2,]    4    5    6</code></pre>
<p>By default, elements from the input vector <code>1:6</code> above are arranged in the matrix <code>m</code> by column - so putting the values in the first column, and after that is filled continuing on the second column, until all entries are filled. You can change this by using <code>byrow = TRUE</code> in the function call (as above).</p>
<p>By default, a matrix with a single column is made. This can be changed by using <code>ncol</code> within <code>matrix()</code>:</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="data-types-part-1.html#cb450-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">ncol =</span> <span class="dv">2</span> )</span>
<span id="cb450-2"><a href="data-types-part-1.html#cb450-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<p>The class of <code>m</code> is:</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="data-types-part-1.html#cb452-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m )</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>The function <code>str()</code> can be used for matrices as well to give a compact display of the object’s structure/content:</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="data-types-part-1.html#cb454-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( m )</span></code></pre></div>
<pre><code>##  int [1:3, 1:2] 1 2 3 4 5 6</code></pre>
</div>
<div id="dimensions-2" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Dimensions<a href="data-types-part-1.html#dimensions-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Many of the functions used for a <code>data.frame</code> to get rows, columns and dimensions can be used for a matrix:</p>
<ul>
<li><code>ncol()</code> for the number of columns:</li>
</ul>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="data-types-part-1.html#cb456-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>( m )</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<ul>
<li><code>nrow()</code> for the number of rows:</li>
</ul>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="data-types-part-1.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>( m )</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<ul>
<li><code>dim()</code> returns a vector with two elements: number of rows and number of columns:</li>
</ul>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="data-types-part-1.html#cb460-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>( m )</span></code></pre></div>
<pre><code>## [1] 3 2</code></pre>
</div>
<div id="settinggetting-names-of-the-columns-and-rows" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Setting/getting names of the columns and rows<a href="data-types-part-1.html#settinggetting-names-of-the-columns-and-rows" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The functions <code>colnames()</code> and <code>rownames()</code> are used to set and get the names of matrix columns and rows:</p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="data-types-part-1.html#cb462-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="data-types-part-1.html#cb464-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span> )</span>
<span id="cb464-2"><a href="data-types-part-1.html#cb464-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      A B
## [1,] 1 4
## [2,] 2 5
## [3,] 3 6</code></pre>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="data-types-part-1.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>, <span class="st">&quot;Z&quot;</span> )</span>
<span id="cb466-2"><a href="data-types-part-1.html#cb466-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<p>To get names use:</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="data-types-part-1.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( m )</span></code></pre></div>
<pre><code>## [1] &quot;X&quot; &quot;Y&quot; &quot;Z&quot;</code></pre>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="data-types-part-1.html#cb470-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( m )</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;B&quot;</code></pre>
</div>
<div id="getting-matrix-elements" class="section level3 hasAnchor" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> Getting matrix elements<a href="data-types-part-1.html#getting-matrix-elements" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The single square-brackets notation with two arguments <code>[ row(s), col(s) ]</code> can be used to get specified row(s) and column(s). By default single rows/cols will get reduced to a vector.</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="data-types-part-1.html#cb472-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="dv">3</span>, <span class="dv">1</span> ]</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="data-types-part-1.html#cb474-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">3</span> ), <span class="dv">1</span> ]</span></code></pre></div>
<pre><code>## Y Z 
## 2 3</code></pre>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="data-types-part-1.html#cb476-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">3</span> ), <span class="fu">c</span>( <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span> ) ]</span></code></pre></div>
<pre><code>##   B A
## Y 5 2
## Z 6 3</code></pre>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="data-types-part-1.html#cb478-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( F, T, T ), <span class="fu">c</span>( <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span> ) ]</span></code></pre></div>
<pre><code>##   B A
## Y 5 2
## Z 6 3</code></pre>
<p>As for a <code>data.frame</code>, an empty index field selects all indices in that field. So, to select all rows and columns <code>B</code> and <code>A</code>, we can use:</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="data-types-part-1.html#cb480-1" aria-hidden="true" tabindex="-1"></a>m[ , <span class="fu">c</span>(<span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span>)]</span></code></pre></div>
<pre><code>##   B A
## X 4 1
## Y 5 2
## Z 6 3</code></pre>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="data-types-part-1.html#cb482-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( <span class="st">&quot;Z&quot;</span>, <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span> ), ]</span></code></pre></div>
<pre><code>##   A B
## Z 3 6
## X 1 4
## Y 2 5</code></pre>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="data-types-part-1.html#cb484-1" aria-hidden="true" tabindex="-1"></a>m[ , ]</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<p>The output class of a few elements of a matrix is still a matrix:</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="data-types-part-1.html#cb486-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">3</span> ), <span class="fu">c</span>( <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span> ) ] )</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>However, the class of a single entry is just the class of that entry:</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="data-types-part-1.html#cb488-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m[ <span class="dv">3</span>, <span class="dv">1</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>When assessing/extracting elements of a matrix, we cannot leave out the comma - which is possible for a <code>data.frame</code> because then by default a column is selected:</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="data-types-part-1.html#cb490-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="dv">1</span> ]</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
</div>
<div id="useful-matrix-functions" class="section level3 hasAnchor" number="2.4.6">
<h3><span class="header-section-number">2.4.6</span> Useful matrix functions<a href="data-types-part-1.html#useful-matrix-functions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Short summary of matrix operations: <a href="http://www.statmethods.net/advstats/matrix.html" class="uri">http://www.statmethods.net/advstats/matrix.html</a></p>
<div id="rowcolumns-meanssums" class="section level4 hasAnchor" number="2.4.6.1">
<h4><span class="header-section-number">2.4.6.1</span> Row/columns means/sums<a href="data-types-part-1.html#rowcolumns-meanssums" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="data-types-part-1.html#cb492-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="data-types-part-1.html#cb494-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowMeans</span>( m )</span></code></pre></div>
<pre><code>##   X   Y   Z 
## 2.5 3.5 4.5</code></pre>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="data-types-part-1.html#cb496-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowSums</span>( m )</span></code></pre></div>
<pre><code>## X Y Z 
## 5 7 9</code></pre>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="data-types-part-1.html#cb498-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>( m )</span></code></pre></div>
<pre><code>## A B 
## 2 5</code></pre>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="data-types-part-1.html#cb500-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>( m )</span></code></pre></div>
<pre><code>##  A  B 
##  6 15</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/05_matrices.tasks.nocode.html#createSummarize">the task(s)</a>, and check your solution(s) <a href="exercises/05_matrices.tasks.code.html#createSummarize">here</a>.</p>
</blockquote>
<hr />
</div>
<div id="reducing-dimensions" class="section level4 hasAnchor" number="2.4.6.2">
<h4><span class="header-section-number">2.4.6.2</span> (*) Reducing dimensions<a href="data-types-part-1.html#reducing-dimensions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When selecting entries from a single column, the result will no longer be a matrix:</p>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="data-types-part-1.html#cb502-1" aria-hidden="true" tabindex="-1"></a>m[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">2</span>] </span></code></pre></div>
<pre><code>## X Y Z 
## 4 5 6</code></pre>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="data-types-part-1.html#cb504-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">2</span>] )</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>This means that some functions that specifically work for matrices, but not for vectors, will no longer work. For example <code>dim()</code> does not return a number:</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="data-types-part-1.html#cb506-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>( m[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">2</span>]  )</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>Of course, functions for vectors work:</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="data-types-part-1.html#cb508-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>( m[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">2</span>] )</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>This happens because the result can be indexed by a single dimension, so the now-obsolete dimension is dropped by default. This can create problems when writing scripts, as functions such as <code>dim()</code> may need to be used. It can therefore be useful to guarantee that the result has the same number of dimensions as the original object, so that functions such as <code>dim()</code> still work, even if a selection may have meant that a vector (rather than a matrix) is returned. In such cases, the argument <code>drop</code> can be used to make sure that all dimensions of the original object are preserved (or not dropped).</p>
<p>For example, the following selection yields a vector, and <code>dim()</code> returns <code>NULL</code>:</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="data-types-part-1.html#cb510-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="dv">3</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span> ]</span></code></pre></div>
<pre><code>## A B 
## 3 6</code></pre>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="data-types-part-1.html#cb512-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(m[ <span class="dv">3</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span> ])</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>By using <code>drop = FALSE</code>, all dimensions are preserved:</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="data-types-part-1.html#cb514-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="dv">3</span>, <span class="dv">1</span>, drop <span class="ot">=</span> <span class="cn">FALSE</span> ]</span></code></pre></div>
<pre><code>##   A
## Z 3</code></pre>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="data-types-part-1.html#cb516-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(m[ <span class="dv">3</span>, <span class="dv">1</span>, <span class="at">drop =</span> <span class="cn">FALSE</span> ])</span></code></pre></div>
<pre><code>## [1] 1 1</code></pre>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="data-types-part-1.html#cb518-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m[ <span class="dv">3</span>, <span class="dv">1</span>, <span class="at">drop =</span> <span class="cn">FALSE</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
</div>
<div id="transposition" class="section level4 hasAnchor" number="2.4.6.3">
<h4><span class="header-section-number">2.4.6.3</span> (*) Transposition<a href="data-types-part-1.html#transposition" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb520-1"><a href="data-types-part-1.html#cb520-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">nrow =</span> <span class="dv">3</span> );</span>
<span id="cb520-2"><a href="data-types-part-1.html#cb520-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span> )</span>
<span id="cb520-3"><a href="data-types-part-1.html#cb520-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>, <span class="st">&quot;Z&quot;</span> )</span>
<span id="cb520-4"><a href="data-types-part-1.html#cb520-4" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="data-types-part-1.html#cb522-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(m)</span></code></pre></div>
<pre><code>##   X Y Z
## A 1 2 3
## B 4 5 6</code></pre>
</div>
<div id="matrix-multiplication" class="section level4 hasAnchor" number="2.4.6.4">
<h4><span class="header-section-number">2.4.6.4</span> (*) Matrix multiplication<a href="data-types-part-1.html#matrix-multiplication" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="data-types-part-1.html#cb524-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="data-types-part-1.html#cb526-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>( m )</span></code></pre></div>
<pre><code>##   X Y Z
## A 1 2 3
## B 4 5 6</code></pre>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="data-types-part-1.html#cb528-1" aria-hidden="true" tabindex="-1"></a>m <span class="sc">%*%</span> <span class="fu">t</span>( m )</span></code></pre></div>
<pre><code>##    X  Y  Z
## X 17 22 27
## Y 22 29 36
## Z 27 36 45</code></pre>
</div>
<div id="element-wise-multiplication" class="section level4 hasAnchor" number="2.4.6.5">
<h4><span class="header-section-number">2.4.6.5</span> (*) Element-wise multiplication<a href="data-types-part-1.html#element-wise-multiplication" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="data-types-part-1.html#cb530-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="data-types-part-1.html#cb532-1" aria-hidden="true" tabindex="-1"></a>m<span class="sc">+</span><span class="dv">1</span></span></code></pre></div>
<pre><code>##   A B
## X 2 5
## Y 3 6
## Z 4 7</code></pre>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="data-types-part-1.html#cb534-1" aria-hidden="true" tabindex="-1"></a>m <span class="sc">*</span> (m<span class="sc">+</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>##    A  B
## X  2 20
## Y  6 30
## Z 12 42</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="exercises/05_matrices.tasks.nocode.html#corMatrix">the task(s)</a>, and check your solution(s) <a href="exercises/05_matrices.tasks.code.html#corMatrix">here</a>.</p>
</blockquote>
<hr />

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basics-of-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-types-part-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
